version: "3.8"

services: 
    db:
        image: postgres
        restart: always
        container_name: db
        environment: 
            POSTGRES_USER : ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE}

    api:
        image: node:12
        container_name: api
        restart: always
        depends_on: 
            - db
        ports: 
            - 4560:4560
        volumes: 
            - .:/usr/src/app
        working_dir: /usr/src/app
        command: 
            - npx knex migrate:latest
            - npm start


    
        